---
- name: Install Clickhouse
  hosts: clickhouse
  debugger: never
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
      tags: clickhouse
  tasks:
    - block:
        - name: Get clickhouse distrib noarch Get clickhouse distrib noarch  from {{ main_package_path.path }}
          ansible.builtin.get_url:
            url: "{{ main_package_path.path }}{{ item }}-{{ main_package_path.version }}.noarch.rpm"
            dest: "./{{ item }}-{{ main_package_path.version }}.rpm"
          with_items: "{{ clickhouse_packages_noarch }}"
        - name: Get clickhouse distrib from {{ main_package_path.path }}
          ansible.builtin.get_url:
            url: "{{ main_package_path.path }}{{ item }}-{{ main_package_path.version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ main_package_path.version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib noarch Get clickhouse distrib from {{ rescue_package_path.path }}
          ansible.builtin.get_url:
            url: "{{ rescue_package_path.path }}{{ item }}-{{ rescue_package_path.version }}.noarch.rpm"
            dest: "./{{ item }}-{{ rescue_package_path.version }}.rpm"
          with_items: "{{ clickhouse_packages_noarch }}"
        - name: Get clickhouse distrib from {{ rescue_package_path.path }}
          ansible.builtin.get_url:
            url: "{{ rescue_package_path.path }}{{ item }}-{{ rescue_package_path.version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ rescue_package_path.version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      tags:
        - clickhouse
        - wipe_pkg
    - block:
        - name: Install clickhouse packages
          ansible.builtin.yum:
            name:
              - clickhouse-common-static-{{ clickhouse_version }}.rpm
              - clickhouse-client-{{ clickhouse_version }}.rpm
              - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
      tags:
        - clickhouse

    - block:
        - name: Start clickhouse service
          ansible.builtin.service:
            name: clickhouse-server
            state: restarted
    - block:
        - name: Create database
          ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
          register: create_db
          failed_when: create_db.rc != 0 and create_db.rc !=82
          changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  tasks:
    - name: Create directrory for vector "{{ vector_dir }}"
      file:
        path: "{{ vector_dir }}"
        mode: 0755
        state: directory
      tags: vector

    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.27.0/vector-0.27.0-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/tmp/vector-0.27.0-x86_64-unknown-linux-gnu.tar.gz"

    - name: Extract vector in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/vector-0.27.0-x86_64-unknown-linux-gnu.tar.gz"
        dest: "{{ vector_dir }}"
        extra_opts: ['--strip-components=2']
      tags:
        - vector
