---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse-role

# Play для установки Vector
# установку вектора заменил на deb пакет и добавил шаблон конфига
- name: Install Vector
  hosts: vector
  roles:
    - role: vector-role

# Play для установки Lighthouse
- name: Install Lighthouse
  hosts: lighthouse
  handlers:
# Вешаем handler для старта и настройки NGINX
    - name: Reload nginx service
      become: true
      ansible.builtin.service:
        name: nginx.service
        enabled: true
        state: restarted
      tags: lighthouse
  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      tags: lighthouse

    - name: install common packages
      become: true
      ansible.builtin.apt:
        name:
          - git
          - curl
        update_cache: yes
      tags: lighthouse

    - name: install nginx latest version
      ansible.builtin.apt:
        name:
          - nginx
        state: latest
      tags: lighthouse
  roles:
    - role: lighthouse-role
# Печатаем URL Lighthouse c указанием пользователя clickhouse
  post_tasks:
    - name: Show connect URL lighthouse
      debug:
        msg: "http://{{ hostvars['nginx-host'].ansible_host }}/#http://{{ hostvars['clickhouse-host'].ansible_host }}:8123/?user={{ clickhouse_user }}"
      tags: lighthouse