version: 3
parallel_apply: true
parallel_plan: true
projects:
- name: project74
  dir: .
  workspace: stage
  delete_source_branch_on_merge: true
  autoplan:
    when_modified: ["../modules/**/*.tf", "*.tf"]
    enabled: true
- name: project74
  dir: .
  workspace: prod
  terraform_version: v1.3.6
  autoplan:
    when_modified: ["../modules/**/*.tf", "*.tf"]
    enabled: true