gh-user: '1nxs'
gh-token: '$TOKEN'

repos:
- id: github.com/1nxs/07-terraform-04-teamwork/
  branch: main
  apply_requirements: [approved, mergeable]
  allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
  allow_custom_workflows: true
  workflow: myworkflow

workflows:
  myworkflow:
    plan:
      steps:
      - init
      - plan:
          extra_args: ["-lock", "false"]
    apply:
      steps:
      - apply