---
# vector_version: "0.27.1"
vector_distro:
  path: "https://packages.timber.io/vector/"
  version: "0.27.1"
  package: "vector_0.27.1-1_amd64.deb"
vector_config_path: /etc/vector/vector.yaml
vector_config:
  sources:
    internal_logs:
      type: internal_logs
    local_logs:
      type: file
      include:
        - /var/log/**/*.log
      read_from: beginning
